<a href="https://colab.research.google.com/github/aypy01/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
##Overview
Numpy is a library to do the maths and msostly is vector form.
There are many function which can be performed so it replaced the Matlab.
Numpy is a module which a List can perform but Numpy is faster than Lists.
The reason of Numpy to be faster is beceause the storage is side by side and not like list's pointer method . Due to this cache memory arrangement is also proper and not scattered . The SimD vectorization is fast for Numpy.

Another benefit is that Numpy array can be multiply directly eg
numpy.array1([1,2,3]) x numpy.array([4,5,6]) is possible

Numpy array can represent 1-D,2-D,3-D,4-D... data and the default of data type is int64 bit while it can also be represented in 32, 16,8-bit too

Numpy is used in M/L, computer vision in processing the image etc

In [ ]:
#Installing the Numpy
!pip install Numpy

In [ ]:
#Loading the library
import numpy as np


##Array

In [ ]:
#Without mentioning the datatype:meaning the dtype will be 64 bits as a default
a=np.array([1,2,3])

b=np.array([[4,5,6],[7,8,9]])

#With mentioning the specific datatype
a=np.array([1,2,3],dtype='int32')

b=np.array([[4,5,6],[7,8,9]],dtype='int32')


###Dimention

In [ ]:
#Getting Dimention
print(a.ndim)
print(b.ndim)

1
2


###Shape

In [ ]:
#Getting Shape i.e: row &col
print(a.shape)
print(b.shape)

(3,)
(2, 3)


###Data Type

In [ ]:
#Getting Type
print(a.dtype)
print(b.dtype)

int32
int32


###Size

In [ ]:
#Getting Size

print(a.itemsize) #Hows its 4...does it have to do with dtype
print(b.itemsize)

4
4


In [ ]:
#Total Size
print(a.nbytes)
print(b.nbytes) #why the out put is 12 and 24??

12
24


###Elements

In [ ]:
#Getting number of elements , not the size
print(a.size) #3 as the element is 1-d row is 3
print(b.size) #row and col in total =6

3
6


##Accessing/Modifying any specific element,row,col

In [ ]:
a=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]]) #Making 2-d array
print(a)

#Now if i want to get the element 14
print(a[1,5]) #I will specify row and colto acess:Remember the python indes starts with 0

#To get Specific row
print(a[0,:])

#To get specific col
print(a[:,3])



[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
14
[1 2 3 4 5 6 7 8]
[ 4 12]


###Indexing/Slicing

In [ ]:

#we can acess like [start index: end index : step size]
print(a[1,3:-2: 2])

#changing the value of element
a[1,5]=20
print(a) #See now 1,5 is 20 instead of 14
#for changing whole row
a[1,:]=[0,0,0,0,0,0,0,0]
print(a)

#For cahnging whole colomn
a[:,3]=[-1,-1]
print(a)

[12 14]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 20 15 16]]
[[1 2 3 4 5 6 7 8]
 [0 0 0 0 0 0 0 0]]
[[ 1  2  3 -1  5  6  7  8]
 [ 0  0  0 -1  0  0  0  0]]


##3-D array

In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

print(b[1,0,1]) #to get the element 6


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6


##Array Types
This section shows how to create arrays filled with:
- Zeros
- Ones
- Custom values
- Random numbers (both floats and integers)
- Identity matrices
- Repeated arrays
- Copies of arrays

All examples include shapes and datatype usage explanations.

In [ ]:
# Create a 3x2 array filled with zeros
z = np.zeros((3, 2))  # 3 rows, 2 columns
print("Zeros array (3x2):\n", z)

Zeros array (3x2):
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Create a 2x3 array filled with ones (as integers)
o = np.ones((2, 3), dtype='int32')
print("Ones array (2x3, int):\n", o)


Ones array (2x3, int):
 [[1 1 1]
 [1 1 1]]


In [ ]:
# Create a 2x3 array filled with ones (as integers)
o = np.ones((2, 3), dtype='int32')
print("Ones array (2x3, int):\n", o)


Ones array (2x3, int):
 [[1 1 1]
 [1 1 1]]


In [ ]:
# Create a 3x3 array filled with a specific number (68)
f = np.full((3, 3), 68, dtype='int64')
print("Full array (3x3 filled with 68):\n", f)


Full array (3x3 filled with 68):
 [[68 68 68]
 [68 68 68]
 [68 68 68]]


In [ ]:
#  Create a new array with same shape as `f` but filled with a different number
# `np.full_like` copies the shape and dtype (unless overridden) from another array
fl = np.full_like(f, 69, dtype='int32')  # 69s in same shape as `f`
print("Full-like array (same shape as f, filled with 69):\n", fl)


Full-like array (same shape as f, filled with 69):
 [[69 69 69]
 [69 69 69]
 [69 69 69]]


In [ ]:
#  Generate a 3x2 matrix with random decimal values between 0 and 1
rd = np.random.rand(3, 2)
print("Random decimal array (3x2):\n", rd)


Random decimal array (3x2):
 [[0.67468574 0.00381582]
 [0.04214733 0.45839005]
 [0.955979   0.63792066]]


In [ ]:
#  Generate a 3x3 matrix of random integers in the range [0, 10)
ri = np.random.randint(0, 10, size=(3, 3))  # 0 inclusive, 10 exclusive
print("Random integer array (3x3, values from 0 to 9):\n", ri)


Random integer array (3x3, values from 0 to 9):
 [[3 7 7]
 [5 4 2]
 [2 4 0]]


In [ ]:
#  Create a 3x3 identity matrix (diagonal of 1s)
identity = np.identity(3, dtype='int32')
print("Identity matrix (3x3):\n", identity)


Identity matrix (3x3):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#  Repeating elements of arrays

# Start with a single row 2D array
array = np.array([[1, 2, 3]])

# Repeat all elements in a flattened 1D format (default axis)
repeat = np.repeat(array, 4)
print("Repeated elements (flattened):\n", repeat)

print()  # Blank line

# Repeat the row 3 times along axis=0 (row-wise)
repeat2 = np.repeat(array, 3, axis=0)
print("Repeated rows (axis=0):\n", repeat2)


Repeated elements (flattened):
 [1 1 1 1 2 2 2 2 3 3 3 3]

Repeated rows (axis=0):
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Copying arrays properly

original = np.array([3, 2, 1])

# Use .copy() to make a deep copy (not a reference)
copy = original.copy()

# Modify the copy
copy[0] = 77

print("Original array (unchanged):", original)
print("Modified copy of array:", copy)


Original array (unchanged): [3 2 1]
Modified copy of array: [77  2  1]


##Mathematics  Operations
- Addition
- Subtraction
- Multiplication
- Division

In [ ]:

# Addition (element-wise)
# Start with a 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# Add 2 to every element in the array
a += 2
print("After addition (a += 2):\n", a)

# Expected Output:
# [[ 3  4  5  6]
#  [ 7  8  9 10]]



After addition (a += 2):
 [[ 3  4  5  6]
 [ 7  8  9 10]]


In [ ]:
# Subtraction (element-wise)
# Make a copy of array `a` and subtract 5 from every element
s = a.copy()
s -= 5
print("After subtraction (s = a - 5):\n", s)

# Expected Output:
# [[-2 -1  0  1]
#  [ 2  3  4  5]]


After subtraction (s = a - 5):
 [[-2 -1  0  1]
 [ 2  3  4  5]]


In [ ]:
# Multiplication (element-wise)
# Multiply every element in `s` by 6
m = s.copy()
m *= 6
print("After multiplication (m = s * 6):\n", m)

# Expected Output:
# [[-12  -6   0   6]
#  [ 12  18  24  30]]


After multiplication (m = s * 6):
 [[-12  -6   0   6]
 [ 12  18  24  30]]


In [ ]:
#  Division (element-wise)
# Divide every element in `m` by 2
d = m.copy()
d = d / 2  # or use d /= 2
print("After division (d = m / 2):\n", d)

# Expected Output:
# [[ -6.  -3.   0.   3.]
#  [  6.   9.  12.  15.]]


After division (d = m / 2):
 [[-6. -3.  0.  3.]
 [ 6.  9. 12. 15.]]


## NumPy Vector Arithmetic: Addition, Squaring & Trigonometry

In this section:

- How to add two arrays (vectors)
- Element-wise squaring of a NumPy array
- Applying trigonometric functions: `sin()` and `cos()`




In [ ]:
# Element-wise Addition of Two Arrays
a = np.array([9, 8, 7])
b = np.array([7, 8, 9])

# Add corresponding elements of `a` and `b`
total = a + b
print("Sum of arrays:\n", total)

# Note:
# Both arrays must have the same shape (same number of elements) for element-wise operations.
# Output: [16 16 16]


Sum of arrays:
 [16 16 16]


In [ ]:
#  Squaring the Elements
# Use **2 to square each element of the array
square = total.copy() ** 2
print("Element-wise square of the sum:\n", square)

# Output: [256 256 256]


Element-wise square of the sum:
 [256 256 256]


In [ ]:
# Applying the Sine Function
# Computes sine of each element (input in radians)
sin_func = np.sin(square.copy())
print("Sine of each squared element:\n", sin_func)


Sine of each squared element:
 [-0.99920803 -0.99920803 -0.99920803]


In [ ]:
# Applying the Cosine Function
cos_func = np.cos(square.copy())
print("Cosine of each squared element:\n", cos_func)


Cosine of each squared element:
 [-0.03979076 -0.03979076 -0.03979076]


##Linear Algebra
In this section, we’ll explore how to perform matrix multiplication using `np.matmul()` — a key operation in linear algebra, machine learning, and scientific computing.

In [ ]:
# Define a matrix of all 1s with shape (2 rows, 3 columns)
a = np.ones((2, 3))
print("Matrix A:\n", a)

# Define another matrix filled with 3s, shape (3 rows, 3 columns)
b = np.full((3, 3), 3)
print("Matrix B:\n", b)


Matrix A:
 [[1. 1. 1.]
 [1. 1. 1.]]
Matrix B:
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
#  Matrix Multiplication
# Use np.matmul() or the @ operator to perform matrix multiplication.
# Matrix A has shape (2x3), Matrix B has shape (3x3)
# Resulting matrix will have shape (2x3)
matrix = np.matmul(a, b)
print("Matrix Multiplication (A x B):\n", matrix)

# Explanation:
# Matrix A (2x3) dot Matrix B (3x3) = Resulting Matrix (2x3)


Matrix Multiplication (A x B):
 [[9. 9. 9.]
 [9. 9. 9.]]


##Finding the Determinant of a Matrix in NumPy

In this example, we'll compute the **determinant** of a square matrix using `np.linalg.det()`.

We use a **4×4 identity matrix**, which should always have a determinant of `1`.


In [ ]:
# Create a 4x4 identity matrix with integer data type
a = np.identity(4, dtype='int32')
print("Identity matrix (4x4):\n", a)

# Compute its determinant
det = np.linalg.det(a)
print("Determinant of identity matrix:", det)


Identity matrix (4x4):
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Determinant of identity matrix: 1.0


##Statistics: Min, Max, and Sum

In this section, we'll learn how to compute basic statistical values from NumPy arrays, including:

- Minimum (`np.min`)
- Maximum (`np.max`)
- Sum (`np.sum`)

These are applied across the full array or along specific axes (rows/columns).


In [ ]:
# Create a 2D array
stats = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print("2D Array:\n", stats)


2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Minimum value in the entire array
min_val = np.min(stats)
print("Minimum value:", min_val)


Minimum value: 1


In [ ]:
# Maximum value in the entire array
max_val = np.max(stats)
print("Maximum value:", max_val)


Maximum value: 10


In [ ]:
#  Sum of elements along each column (axis=0)
sum_col = np.sum(stats, axis=0)
print("Sum of each column:", sum_col)

#  Sum of elements along each row (axis=1) — optional
sum_row = np.sum(stats, axis=1)
print("Sum of each row:", sum_row)


Sum of each column: [ 7  9 11 13 15]
Sum of each row: [15 40]


# Reorganizing Arrays with `reshape()`

NumPy allows you to reshape arrays using the `reshape()` method. This is useful when you want to convert a 1D array into a 2D array or change its structure while preserving the data.

In this example, we convert a 1D array of 10 elements into a 2D array with 2 rows and 5 columns.


In [ ]:
#  Create a 1D array with 10 elements
before = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Before reshaping (1D array):\n", before)


Before reshaping (1D array):
 [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Reshape into 2 rows and 5 columns
after = before.reshape((2, 5))
print("After reshaping to (2, 5):\n", after)

# Note:
# The total number of elements must remain the same.
# 1D → 2D reshaping is common in machine learning and image processing.


After reshaping to (2, 5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


##  NumPy Array Stacking: Vertical & Horizontal

Stacking is a way to combine multiple arrays into one. NumPy provides:

- `np.vstack()` to **vertically stack** arrays (along rows)
- `np.hstack()` to **horizontally stack** arrays (along columns)

These are useful when building large arrays from smaller blocks — especially in image processing, data joining, and neural networks.


In [ ]:
#  Define two 1D arrays (vectors)
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])

#  Vertically stack: will stack as separate rows
# Order: v1, v2, v1, v2 → results in a 4x5 matrix
stacked_array = np.vstack([v1, v2, v1, v2])

print(" Vertical stacking of arrays:\n", stacked_array)

# Output:
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [ 1  2  3  4  5]
#  [ 6  7  8  9 10]]


 Vertical stacking of arrays:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#  Define two 2D arrays for horizontal stacking
h1 = np.ones((3, 2))   # 3 rows × 2 columns of ones
h2 = np.zeros((3, 3))  # 3 rows × 3 columns of zeros

#  Horizontally stack: requires same number of rows
# Concatenates columns from both arrays
h_stacked = np.hstack((h1, h2))

print(" Horizontal stacking of arrays:\n", h_stacked)

# Output:
# [[1. 1. 0. 0. 0.]
#  [1. 1. 0. 0. 0.]
#  [1. 1. 0. 0. 0.]]


 Horizontal stacking of arrays:
 [[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


## Loading Data from Text Files with NumPy

NumPy provides powerful tools to load structured data from `.txt` files using `np.genfromtxt()`. This is often used for reading CSV-style numeric datasets.

###  File Used: `data.txt`

>  Ensure that `data.txt` is located in the **same directory** as your Python script or notebook.


In [ ]:
# Load a text file using np.genfromtxt
file = np.genfromtxt("data.txt", delimiter=",")  # Load CSV-style text file

#  What is delimiter?
# The `delimiter=","` tells NumPy to split each line at commas — like reading a CSV.
# You can change it to '\t' for tab-separated files or ' ' for space.

#  Convert data type to int32 for consistency in further operations
file = file.astype('int32')

# Print the loaded matrix
print("Loaded data:\n", file)


Loaded data:
 [[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
# Boolean Masking: Create a mask where values are > 50 AND < 98

# You cannot use:
# (file > 50) and (file < 98)
# Because `and` only works with single boolean values, not arrays

#Use bitwise logical operator `&` for element-wise comparison
#print((file>50)) and (file<98)
mask = (file > 50) & (file < 98)
print("Boolean mask for values > 50 and < 98:\n", mask)

# You can also filter values like this:
filtered = file[mask]
print("Filtered values:\n", filtered)


Boolean mask for values > 50 and < 98:
 [[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
Filtered values:
 [75 75 55 78 76 88]
